Repository Rhlverdi/Simple-Program, pull requests merged in 2022-10, with the labels that each got.

#1 add file program CRUD CPP
  main.cpp
Labels: good first issue, hacktoberfest-accepted

#2 add file program priimesNumber.cpp
  primesNumber.cpp
Labels: hacktoberfest-accepted

#3 update readme.md
  README.md
Labels: documentation, hacktoberfest-accepted
